dianedup/cookinglab

.gitignore
app/controllers/owner/recipes_controller.rb

Controller owner

---

db/migrate/20190329112921_add_upvote_published_on_servings_to_recipes.rb
db/migrate/20190329133529_change_column_published_on_to_recipes.rb
db/schema.rb

recipes table updated

---

app/views/recipes/index.html.erb

fix avatar size on index

---

app/assets/stylesheets/pages/_edit_owner_recipe.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/owner/doses_controller.rb
app/controllers/owner/recipes_controller.rb
app/controllers/owner/steps_controller.rb
app/models/recipe.rb
app/models/step.rb
app/views/owner/recipes/edit.html.erb
config/routes.rb

add-edit-delete steps, add-edit-delete doses of ingredients

Enable owner to edit recipe subtitle, times, description, steps and doses

---

app/views/shared/_navbar.html.erb

J'ai traduits la dropdown de la NavBar en français

turn navbar to french

---

app/views/owner/dashboards/show.html.erb
app/views/owner/recipes/new.html.erb
app/views/shared/_navbar.html.erb

J'ai ajouter le lien dashboard à la navbar
le btn annuler sur new recipe
et le btn ajouter un recette au dashbaord

Add btn add recipe to dashboard

---

app/models/ingredient.rb
app/models/utensil.rb

J'ai ajouter des validations à Ustensile et Ingredients pour que la presence de leur name soit true

add validates to ustensil and ingredients

---

app/controllers/owner/dashboards_controller.rb
app/controllers/recipes_controller.rb

J'ai ajouter une notion de tri par date sur l'index et sur le dashboard

Order card index by date

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_show.scss
app/views/shared/_navbar.html.erb
db/schema.rb

image de mon avatar fixé dans la navbar 
un peu de padding et de margin liés à la navbar

avatar thierry fixed and padding and margin

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_show.scss
app/controllers/copies_controller.rb
app/services/recipes/create_variant_service.rb
app/views/recipes/show.html.erb

- create creation variant flow from Original recipe #Show to Variant #Edit 
- fix display of variants card
- turn 'back to original recipe' in a button
- filter variants on Original recipe #Show on 'published: true'

Create variant from show

---

app/assets/stylesheets/components/_navbar.scss

on a retrouvé la main sur le clique de l'avatar de la navbar
ajout d'un léger padding en haut et en bas
le profil a été corrigé par Diane sur une autre branche

navbar updated with hand click and padding

---

db/migrate/20190402140736_change_column_subtitle_to_recipes.rb
db/schema.rb

Le subtitle par défaut a été corrigé en "originale"

subtitle by default modified in originale

---

app/controllers/owner/recipes_controller.rb

add permission to edit and update

add permission to edit and update

---

app/models/recipe.rb
app/views/recipes/index.html.erb

le count variants avec published = true est fixé

recipe.variants.count  with published=true fixed

---

app/views/owner/recipes/edit.html.erb

Le "sous titre" s'affiche uniquement quand le kind de la recette est variante, et j'ai changer "sous titre" par "nom de votre variante"

change the display for susbtitle recipes#edit

---

app/views/owner/recipes/new.html.erb

Fix btn with arrow on dashboard

---

app/assets/stylesheets/components/_card.scss
app/views/owner/dashboards/show.html.erb

J'ai finalement ajouter le lien sur le titre de la card et non sur toute l'image

add link to show on title

---

app/controllers/owner/recipes_controller.rb

add published on for recipes

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

Signed-off-by: Matthias Geoffroy <matthiasgeoffroy@gmail.com>

Add my recipes button outside of navbar drop down toggle

---

app/views/owner/recipes/edit.html.erb

Signed-off-by: Matthias Geoffroy <matthiasgeoffroy@gmail.com>

Modif return to dashboard button

---

app/controllers/owner/changes_proposals_controller.rb
app/views/owner/dashboards/show.html.erb
config/routes.rb

without modifying original recipe

accept or refuse cp on dashboard 1/2

---

Gemfile
Gemfile.lock
app/views/devise/shared/_links.html.erb
config/application.rb

traduction de devise et des message d'erreur de simple form for en francais

turn app to french

---

app/controllers/recipes_controller.rb
app/views/recipes/show.html.erb
db/migrate/20190404100040_add_default_value_to_recipes.rb
db/schema.rb

J'ai fait le calcul des ingredient et j'ai mis 4 comme valeur par default pour servings

Fix sum on ingredients

---

app/assets/stylesheets/pages/_dashboard.scss
app/views/owner/dashboards/show.html.erb
app/views/recipes/_upvote.html.erb

Le problème du sous titre est fixé

pb subtitle in my recipes fixed

---

app/assets/stylesheets/pages/_show.scss
app/views/recipes/show.html.erb

Signed-off-by: Matthias Geoffroy <matthiasgeoffroy@gmail.com>

Show front modifications

---

app/views/owner/dashboards/show.html.erb

J'ai fixer le link to pour aller sur la show a partir d'une card du dashboard. Tu puex y acceder uniquement si la recette est publiée

fix hover title on dashboard

---

app/views/owner/recipes/edit.html.erb

j'ai transformer tous les petits formulaires da la premiere partie du Edit en 1 seul

make only one form for header edit form

---

app/views/owner/dashboards/show.html.erb
app/views/owner/recipes/edit.html.erb

j'ai fixer le form edit en fonction du kind de la recipe

Fix form by recipe kind

---

db/seeds.rb

modification des seeds avec changes_proposal

seeds updated V4

---

app/controllers/owner/changes_proposals_controller.rb
app/services/recipes/create_copy_service.rb
app/services/recipes/merge_cp_on_original_recipe_service.rb

When the owner of a recipe receives a changes proposal and accept it, the changes are merged on the original recipe.

Merge change proposal
